spring:
  datasource:
    username: root
    password: root123456
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 50000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
#告知mybatis-plus去哪里找mapper文件
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
#配置自增主键，这样实体上的tableid注解就不用挨个配置了
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: debug
